ci: disable e2e

diff --git a/.github/workflows/e2e-ubuntu.yml b/.github/workflows/e2e-ubuntu.yml
--- a/.github/workflows/e2e-ubuntu.yml
+++ b/.github/workflows/e2e-ubuntu.yml
@@ -28,37 +28,37 @@ jobs:
           echo "Temporarily disable this job due to port 53 conflict with dnsmasq"
           exit 0
 
-      - name: 📦 Check out the codebase
-        uses: actions/checkout@v4.1.6
-
-      - name: 🐳 Set up Docker
-        run: |
-          apt update
-          apt install -y curl make apt-utils net-tools procps iproute2 iputils-ping
-          curl -fsSL https://get.docker.com -o get-docker.sh
-          sh get-docker.sh
-
-      - name: 🌎 Generate .env file
-        run: make env
-
-      - name: 🏗️ Start docker-compose services
-        run: |
-          make up
-
-      - name: 🧪 Test DNS Resolver with dig
-        run: |
-          if ! dig @127.0.0.1 -p 53 any-domain.docker +short; then
-            echo "DNS resolution failed!"
-            exit 1
-          fi
-
-      - name: 🧪 Test DNS resolver with ping
-        run: |
-          if ! ping -c 3 any-domain.docker; then
-            echo "Ping test failed!"
-            exit 1
-          fi
-
-      - name: ⚙️ Stop docker-compose services
-        if: always()
-        run: make down
+#      - name: 📦 Check out the codebase
+#        uses: actions/checkout@v4.1.6
+#
+#      - name: 🐳 Set up Docker
+#        run: |
+#          apt update
+#          apt install -y curl make apt-utils net-tools procps iproute2 iputils-ping
+#          curl -fsSL https://get.docker.com -o get-docker.sh
+#          sh get-docker.sh
+#
+#      - name: 🌎 Generate .env file
+#        run: make env
+#
+#      - name: 🏗️ Start docker-compose services
+#        run: |
+#          make up
+#
+#      - name: 🧪 Test DNS Resolver with dig
+#        run: |
+#          if ! dig @127.0.0.1 -p 53 any-domain.docker +short; then
+#            echo "DNS resolution failed!"
+#            exit 1
+#          fi
+#
+#      - name: 🧪 Test DNS resolver with ping
+#        run: |
+#          if ! ping -c 3 any-domain.docker; then
+#            echo "Ping test failed!"
+#            exit 1
+#          fi
+#
+#      - name: ⚙️ Stop docker-compose services
+#        if: always()
+#        run: make down
